### ISSUE TITLE
3 bugs 

### ISSUE THREAD

**Issue by AlexisTM** [h3rb/gml-pro#5]
The actual code do not compile because of 3 errors.

```
	Error in Script 'init_audio' at Line 89, Position 30: Unknown function or script: random_posneg
	Error in Script 'RIGHT_ID' at Line 1, Position 1: Unexpected symbol in expression.
	Error in Script 'render_radio' at Line 27, Position 18: Unknown function or script: FLOOR
```
	
The second comes from the `#define`, which are read even commented. In GameMaker `#define` creates a new tab in the script. 

https://github.com/h3rb/gml-pro/blob/master/GML-Pro-Pack2.gmx/scripts/CubeMappedSphere.gml#L143

The third comes from the floor command which should be in without capital letters

https://github.com/h3rb/gml-pro/blob/master/GML-Pro-Pack2.gmx/scripts/render_radio.gml#L27

**Comment by AlexisTM** [comment]
Also, https://github.com/h3rb/gml-pro/blob/master/GML-Pro-Pack2.gmx/scripts/sym_copy_climb.gml#L2 miss a coma

**Comment by h3rb** [comment]
I will address these when I've got a moment - possibly sometime in the next week.  I want to mention that this is because you've upgraded GameMaker from an earlier version, for which this was written.  Since they changed the audio specification, those things break.  Once these issues are fixed you should be able to use _most_ of GML Pro, though I've heard the rules around off-screen buffers has changed, so I will have to revisit.  Obviously the lionshare of this work is the shaders, which can be easily moved into your project.

**Comment by AlexisTM** [comment]
Indeed, it was with the GML Studio 1.4 :/

This is an awesome repo :D

**Comment by h3rb** [comment]
Thank you Alexis.  

I have fixed the things you have mentioned, but have not tested it.  There were actually 4 things, I think they should all be fixed now.  Thanks for reporting the issue.
